### ISSUE TITLE
SoC Support

### ISSUE THREAD

**Issue by Yankwerks** [xzr467706992/KonaBess#1]
Any chances of support coming for older SoCs? For example, the Snapdragon 730/730G/732G. 
Or has the respective driver been introduced only on those lastest ones that are already supported?
It is funny how no one ever thought of this, good job.

If needed I can provide help.

**Comment by ivan89el** [comment]
Still forgot 720G

**Comment by xzr467706992** [comment]
It seems that sd730 does not have gpu-opp-table built inside dtb, which means this software can never support those chips.

**Comment by Aarqw12** [comment]
> Still forgot 720G

He right its have no gpu-opp-table but definited in gpucc-sdmmagpie.c, 

By default in 720g its 750mhz ( see atoll.dtsi history commit ) but in gpucc-sdmmagpie.c for VDD_GX_HIGH_L1 max value authorized is 825000000.

Also 825mhz is set in atoll.dtsi for GPU speedbin if you look carefully.

If you try you can see phone refuse to use more to 750mhz and kernel panic only (only log kgsl crash in ramoops ). Difficult to say if they are limitation set in other place of kernel like CPU for this soc.( trustzone )

I have only succefully loaded in test 180mhz GPU by using gpu-sdmmagpie.dtsi directly... ( 180mhz is useless I know its test only )

Hope its have helped a little you
