### ISSUE TITLE
Is this method getting blocked by new MIUI weekly update(21.2.4), only one freq slot can be selected above 587(like 865+).

### ISSUE THREAD

**Issue by Originalimoc** [xzr467706992/KonaBess#2]
I'm trying the old version(0.8.1 which worked) now, wait a minute.

**Comment by Originalimoc** [comment]
Repack with 0.8.2: Fail
Trying reflash whole boot img from source.

**Comment by xzr467706992** [comment]
MIUI has done something in their kernel to hide the overclocked frequencies. Someone reported that the overclocked frequencies are still available although they are hidden ( Like what they done on k30s). Whatever, this software can do nothing with it.

**Comment by Originalimoc** [comment]
Failed again.
Well I'll just give up Freq 400 and 441 for now.

**Comment by Originalimoc** [comment]
Yeah, performance is the same, maximum reported freq capped at 670.
But that's a shady AF move from Xiaomi.

**Comment by MlgmXyysd** [comment]
This is probably just a preliminary action. Suggest replacing it with another ROM.

**Comment by Originalimoc** [comment]
Nope it isn't how many different freq can be set, just any above 670 is hidden.

**Comment by Originalimoc** [comment]
@xzr467706992 what known happened to k30s???

**Comment by xzr467706992** [comment]
> @xzr467706992 what known happened to k30s???

K30s has 905mhz OC by default. But those frequencies are all hidden. Only can be activated in antutu benchmark.

**Comment by Originalimoc** [comment]
Well, that's even more shady AF
No wonder it has so much higher GPU score when it first came out and get reviewed by antutu
(Is that illegal?

**Comment by Originalimoc** [comment]
You can see there's a fourth freq table called unknown table3 with 905MHz, now that's an "official" OC baseline guide XD

**Comment by MlgmXyysd** [comment]
May be a hidden benchmark specific performance mode XD

**Comment by Errol1886** [comment]
I am absolutely disgusted with what Xiaomi has did. My Mi 10's gaming performance is now crap because I can no longer overclock the GPU. The 670 MHz max frequency is insufficient for my gaming needs. Gaming performance is now much worst. I tried to downgrade to a previous version of Xioami's EU rom, but my phone won't boot. My phone will only boot if I flash the boot.img from the latest Xioami EU Rom. @Originalimoc did you discover any solutions that will let us access and use the hidden frequencies?

**Comment by Errol1886** [comment]
> I am absolutely disgusted with what Xiaomi has did. My Mi 10's gaming performance is now crap because I can no longer add GPU frequencies higher than 670 MHz . The 670 MHz max GPU frequency that Xioami has now locked in to the kernel is insufficient for my gaming needs. Gaming performance is now much worst. I tried to downgrade to a previous version of Xioami's EU rom, but my phone won't boot. My phone will only boot if I flash the boot.img from the latest Xioami EU Rom. @Originalimoc did you discover any solutions that will let us access and use the hidden frequencies?

I found a solution. I had a old back up boot.img file from the Xioami EU Rom version 21.2.24. I extracted the .img-zImage file from my backed up boot.img file using the Android Kitchen Mobile script. I then replaced the .img-zImage file of the the latest Xiaomi EU rom version with my extracted .img-zImage backed up version. I then used Kona Bess to restore my backed up GPU frequencies text file. Now everything is working perfectly again.

**Comment by Originalimoc** [comment]
@Errol1886 Cool. But I don't think you'll need this though, the ACTUAL OC performance is not capped at 670MHz, just the table you can choose/use on an GPU tuner and readout is hidden. And game turbo utility is also showing correct OC load too(this is weird though given that'll mean game turbo knows the actual operating frequency). So not affecting me on my use case.

**Comment by Errol1886** [comment]
> @Errol1886 Cool. But I don't think you'll need this though, the ACTUAL OC performance is not capped at 670MHz, just the table you can choose/use on an GPU tuner and readout is hidden. And game turbo utility is also showing correct OC load too(this is weird though given that'll mean game turbo knows the actual operating and max frequency). So not affecting me on my use case.

For me the correct OC frequency was not being used. The GPU was only going up to 670 MHz. I tested it with some of my games with my usual graphics settings and the performance of my games was much worst.

**Comment by Originalimoc** [comment]
@Errol1886 well I'm on 21.3.3 now. Not sure 3.10's behaviour.

**Comment by Cooley30** [comment]
Error 1886 I wounder if this will work on android 12 going to give a go aha
