### ISSUE TITLE
Galaxy S10 Lite stuck on the screen right after installing modified kernel

### ISSUE THREAD

**Issue by amaterasushen** [xzr467706992/KonaBess#3]
i have a s10 lite with snapdragon 855, when i'm going to make changes to the frequencies it asks to choose if i have snapdragon 855 or 855+, if i make any changes in tab 855 i get stuck in the samsung logo screen, but if i make changes on the 855+ or change the voltage everything works normally (the phone starts normally).

I used version 0.11. I am going to test old versions now.

![photo_2021-02-17_05-32-38](https://user-images.githubusercontent.com/46272374/108160821-96c20580-70c8-11eb-99ae-cf63b2055a37.jpg)

**Comment by xzr467706992** [comment]
Have you edit the GPU volt table after doing changes in freq table? A frequency must have a corresponding voltage in voltage table, otherwise it ll stuck at logo.

**Comment by amaterasushen** [comment]
> Have you edit the GPU volt table after doing changes in freq table? A frequency must have a corresponding voltage in voltage table, otherwise it ll stuck at logo.

Hi, sorry, it was my mistake. I found that just changing the frequency (even a little bit, it doesn't work.). changing the tension table worked. I was able to overclock 710 MHz.

Could you answer a question for me? what does "bus-freq", "bus-min", "bus-max" mean?

I would like to do a little overclock and decrease the tension, is that possible?

**Comment by xzr467706992** [comment]
> > Have you edit the GPU volt table after doing changes in freq table? A frequency must have a corresponding voltage in voltage table, otherwise it ll stuck at logo.
> 
> Hi, sorry, it was my mistake. I found that just changing the frequency (even a little bit, it doesn't work.). changing the tension table worked. I was able to overclock 710 MHz.
> 
> Could you answer a question for me? what does "bus-freq", "bus-min", "bus-max" mean?
> 
> I would like to do a little overclock and decrease the tension, is that possible?

Click on bus freq and you ll see the description of it.
