### ISSUE TITLE
iqoo neo3打开软件失败

### ISSUE THREAD

**Issue by MusaHao** [xzr467706992/KonaBess#4]
![lADPDiQ3Nx-iffbNCWjNBDg_1080_2408](https://user-images.githubusercontent.com/29720490/108582187-7f0aab80-736c-11eb-9293-9d0c03230a84.jpg)

**Comment by xzr467706992** [comment]
没root还搞机？

**Comment by MusaHao** [comment]
好吧 是网络上把这个宣传的太神了
![Dingtalk_20210220115139](https://user-images.githubusercontent.com/29720490/108583059-17eff580-7372-11eb-9054-4f1f903a524c.jpg)
