### ISSUE TITLE
750G supported or not? Using stock kernel provided by Xiaomi.

### ISSUE THREAD

**Issue by oneironaut2209** [xzr467706992/KonaBess#6]

**Comment by xzr467706992** [comment]
Should work

**Comment by oneironaut2209** [comment]
Device doesn't boot.

**Comment by xzr467706992** [comment]
@oneironaut2209 A frequency must have a corresponding voltage in voltage table, otherwise it ll stuck at logo. Also overclocking too much will also stuck at logo.

**Comment by oneironaut2209** [comment]
Ok so by default 800 mhz is maximum. I edited both to 850 mhz and it did booted. But system crashed when I set minimum frequency to 850 mhz. And normal it doesn't go that high, even with performance governor.
