### ISSUE TITLE
[Question] CPU clock/voltage control on kona

### ISSUE THREAD

**Issue by AXKuhta** [xzr467706992/KonaBess#7]
I wanted to ask, was CPU overclocking ever figured out on kona?

My research led me to the qcom-cpufreq-hw driver which seems to read the frequency/voltage values from some sort of memory-mapped hardware. I was able to read the values at https://github.com/AXKuhta/android_kernel_asus_sm8250/commit/4993c9a76a3f69ef63f032ee359dc43fbb239e83 and https://github.com/AXKuhta/android_kernel_asus_sm8250/commit/d465cc7f3a643135da6bcda20453111e2b1b8345, but nothing I tried could alter them: https://github.com/AXKuhta/android_kernel_asus_sm8250/commit/9985ad21995fc442ffffe393f0902767035ae7c3

Thus it seems that frequency/voltage tables may be fused into the bootrom or may be set somewhere in the early firmware, though I'm just speculating at this point.

**Comment by xzr467706992** [comment]
Here's a explanation from kdrag0n

Starting with the 845 generation, Qualcomm introduced a hardware clock manager dubbed OSM (Operating State Manager). Early during the SoC's development, the kernel was responsible for initializing OSM and the in-kernel OSM driver was much more sophisticated as it held the sole responsibility of configuring OSM for all the CPUs as well as the shared L3 system cache.

In July of 2017, Qualcomm decided to prevent the kernel from modifying these values and designated OSM initialization to the TrustZone secure world instead. Here's the [kernel commit](https://source.codeaurora.org/quic/la/kernel/msm-4.9/commit/?id=cc3e94705337) marking the change. Reverting that commit will NOT unlock it as the change was made to the secure world's firmware. The commit mentions being locked out from the HLOS, which stands for High-Level OS — Linux in this case.

After that change, the kernel simply reads the frequency table out of the few OSM registers it is allowed to access and exposes them to the clk framework as well as cpufreq for the rest of the kernel to use. To initiate a frequency switch, the kernel writes the index of the desired frequency to a special OSM register in memory and then TrustZone/OSM handles the rest based on the table programmed into it. TrustZone reads the tables from the QFPROM, which cannot be mutated by the kernel.

**Comment by AXKuhta** [comment]
That answers it nicely.

No CPU overclocking for us, I guess. It'd take serious reverse engineering effort, if at all possible.

I'll close the issue now. Hopefully if anyone else is wondering this question they'll find it.
